### ISSUE TITLE
Definition file gets ignored.

### ISSUE THREAD

**Issue by Dave3o3** [tfroescher/orchide-builder#1]
Hi,

I downloaded the latest definition jar from releases and placed it into

`~/Library/Application Support/JetBrains/PyCharm2020.3/plugins/orchide/lib/orchide-definitions.jar`

and restarted the IDE. The new collections are still unrecognized.

System and IDE info:
```
PyCharm 2020.3.2 (Professional Edition)
Build #PY-203.6682.179, built on December 30, 2020
Runtime version: 11.0.9.1+11-b1145.63 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: CMD Support, DBN, Key Promoter X, YAML/Ansible support, com.chrisrm.idea.MaterialThemeUI, com.intellij.apacheConfig, com.intellij.ideolog, com.jetbrains.php.framework, com.mallowigi, com.taff.plugin.orchide, ideanginx9, main.kotlin.com.jimschubert.intellij.swaggercodegen, net.seesharpsoft.intellij.plugins.csv, net.vektah.codeglance, nl.jworks.intellij.bootstrap3, org.intellij.RegexpTester, org.intellij.plugins.hcl, com.failfast, zielu.gittoolbox, mobi.hsz.idea.gitignore, org.zalando.intellij.swagger, org.toml.lang, com.jetbrains.twig, com.jetbrains.intellij.datalore, net.ashald.envfile, ru.adelf.idea.dotenv
```

Plugin version: `2020.1.3.0-2019.3`

**Comment by tfroescher** [comment]
Hi,

please use a folder that is independent of the IntelliJ platform. IntelliJ plugin installer cleans up .../plugins/orchide/*.

- Create a new folder anywhere
- Configure that folder in OrchidE Settings (Languages & Frameworks -> OrchidE -> Extension) 
- Use the "Downloader" on the OrchidE settings page to "installed" the jar.

You could also put the jar into you're newly created folder. OrchidE will load it on startup of IntelliJ, but status messages on the settings page might be wrong.

**Comment by Dave3o3** [comment]
That worked, thanks! :)
